# Generated by Django 4.0.6 on 2022-07-25 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dscrp', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'cuisines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeHasSkills',
            fields=[
                ('name', models.OneToOneField(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tmc_app.recipes')),
            ],
            options={
                'db_table': 'recipe_has_skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextRecipes',
            fields=[
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'text_recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YtRecipes',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=44, null=True)),
            ],
            options={
                'db_table': 'yt_recipes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe_has_skills',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Text_recipes',
        ),
        migrations.DeleteModel(
            name='Yt_recipes',
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Recipe_has_skills',
        ),
    ]
