# Generated by Django 4.0.6 on 2022-07-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_app', '0002_cuisines_recipehasskills_textrecipes_ytrecipes_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipes',
            table='recipes',
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skills',
        ),
    ]
