# Generated by Django 4.0.6 on 2022-07-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmc_app', '0005_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dscrp', models.CharField(blank=True, max_length=700, null=True)),
            ],
            options={
                'db_table': 'cuisines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('name', models.CharField(max_length=67, primary_key=True, serialize=False)),
                ('cuisine', models.CharField(blank=True, max_length=16, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('isvalid', models.IntegerField(blank=True, db_column='isValid', null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('tag', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('dscrp', models.CharField(blank=True, max_length=209, null=True)),
            ],
            options={
                'db_table': 'skills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextRecipes',
            fields=[
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'text_recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YtRecipes',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=44, null=True)),
            ],
            options={
                'db_table': 'yt_recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeHasSkills',
            fields=[
                ('name', models.OneToOneField(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tmc_app.recipes')),
            ],
            options={
                'db_table': 'recipe_has_skills',
                'managed': False,
            },
        ),
    ]
