# Generated by Django 4.0.6 on 2022-08-01 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmc_app', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Recipes',
            fields=[
                ('user', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tmc_app.users')),
                ('is_todo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User_Recipes',
                'managed': False,
            },
        ),
    ]
